base_model: NousResearch/Meta-Llama-3-8B-Instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

#chat_template: llama3
datasets:
dataset_prepared_path:
debug: 
deepspeed: 
eval_max_new_tokens: 128
eval_steps: 0
early_stopping_patience: 1
early_stopping_threshold: 0.15
val_set_size: 0.05
evals_per_epoch: 
#flash_attention: true
attention: auto
fp16: false
fsdp: 
fsdp_config: 
lora_modules_to_save:
  - lm_head
gradient_accumulation_steps: 16
gradient_checkpointing: false
dataloader_num_workers: 4
group_by_length: true
adapter: lora
learning_rate: 0.0002
load_in_4bit: false
load_in_8bit: true
local_rank: 
logging_steps: 1
lora_alpha: 256
lora_dropout: 0.1
lora_fan_in_fan_out: 
lora_model_dir: 
lora_r: 128
lora_target_linear: true
lr_scheduler: cosine
max_steps: 2000
eval_steps: 250
save_steps: 250
micro_batch_size: 2
model_type: AutoModelForCausalLM
num_epochs: 10
optimizer: adamw_torch_fused
output_dir: miner_id_24
pad_to_sequence_len: true
#peft_use_dora: true
peft_use_rslora: true
resume_from_checkpoint: 
#s2_attention: 
sample_packing: false
saves_per_epoch: 
seed: 88
sequence_len: 2048
bf16: true
strict: false
tf32: false
tokenizer_type: AutoTokenizer
train_on_inputs: false
trust_remote_code: true
warmup_steps: 100
weight_decay: 0.02
#xformers_attention: 

wandb_project: Gradients-On-Demand
wandb_entity:
wandb_mode: online
wandb_run: your_name
wandb_runid: default

hub_model_id:
hub_repo:
hub_strategy: checkpoint
hub_token:
