adapter: lora
base_model: scb10x/llama-3-typhoon-v1.5-8b-instruct
bf16: true
dataset_prepared_path: null
datasets:
debug: null
deepspeed: null
eval_steps: 250
dataloader_num_workers: 4
eval_max_new_tokens: 128
early_stopping_patience: 1
early_stopping_threshold: 0.15
val_set_size: 0.2
flash_attention: true
fp16: null
gradient_accumulation_steps: 16
#gradient_checkpointing: true
group_by_length: true
hub_model_id: 
hub_repo: null
hub_strategy: checkpoint
hub_token: null
learning_rate: 8e-4
load_in_4bit: false
load_in_8bit: true
local_rank: null
logging_steps: 1
lora_modules_to_save:
    - lm_head
lora_alpha: 128
lora_dropout: 0.1
lora_fan_in_fan_out: null
lora_model_dir: null
#torch_compile: true
lora_r: 64
lora_target_linear: true
lr_scheduler: cosine
max_steps: 1500
micro_batch_size: 1
mlflow_experiment_name: 
model_type: AutoModelForCausalLM
num_epochs: 2
optimizer: adamw_bnb_8bit
output_dir: miner_id_24
pad_to_sequence_len: true
peft_use_rslora: true
resume_from_checkpoint: null
s2_attention: null
sample_packing: false
save_steps: 250
sequence_len: 1536
strict: false
tf32: false
tokenizer_type: AutoTokenizer
train_on_inputs: false
trust_remote_code: true
warmup_steps: 100
weight_decay: 0.05
xformers_attention: null
